#!/bin/bash
# Install `mirror` on PATH as a wrapper over `uv run`. The wrapper resolves the
# project venv on every call, so a new pyproject.toml dependency needs no
# reinstall. A uv tool install froze its dependency set and went stale instead.
set -euo pipefail

project_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
target="$HOME/.local/bin/mirror"

uv tool uninstall mirror >/dev/null 2>&1 || true
mkdir -p "$(dirname "$target")"

cat > "$target" <<EOF
#!/bin/bash
# Generated by bs/install.sh. Do not edit.
# uv resyncs the project venv from pyproject.toml on every call.
exec uv run --project "$project_dir" mirror "\$@"
EOF

chmod +x "$target"
echo "installed $target -> uv run --project $project_dir mirror"
